name: cross_platform_product_listing_assessment
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
    sdk: ^3.6.1

dependencies:
    flutter:
        sdk: flutter

    http: ^1.3.0
    equatable: ^2.0.7
    http_mock_adapter: ^0.4.2
    get_it: ^8.0.3
    shared_preferences: ^2.5.1
    flutter_bloc: ^9.0.0
    bloc_test: ^10.0.0
    hydrated_bloc: ^10.0.0
    path_provider: ^2.1.5
    flutter_screenutil: ^5.9.3
    auto_route: ^9.3.0+1

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^5.0.0
    mockito: ^5.4.5
    build_runner: ^2.4.14
    auto_route_generator: ^9.3.1

flutter:
    uses-material-design: true
