name: Build Flutter APK

on:
    push:
        branches:
            - main # Adjust if your main branch is different
    workflow_dispatch: # Allows manual triggering

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Flutter
              uses: subosito/flutter-action@v2
              with:
                  flutter-version: "3.27.2" # Change to your Flutter version

            - name: Install dependencies
              run: flutter pub get

            - name: Build APK
              run: flutter build apk --release

            - name: Upload APK as Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: release-apk
                  path: build/app/outputs/flutter-apk/app-release.apk
                  retention-days: 7 # Keep the APK for 7 days (adjust as needed)
